"""mig_02_additional_columns_in_user_model

Revision ID: 1565b42bcd77
Revises: 2b653bfa1bad
Create Date: 2026-06-04 13:42:32.939221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1565b42bcd77'
down_revision: Union[str, Sequence[str], None] = '2b653bfa1bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('resume_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('skills', sa.ARRAY(sa.String(length=255)), nullable=True))
    op.add_column('users', sa.Column('experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'experience')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'resume_url')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
