"""retrieval_summary_added_in_interview

Revision ID: 269efebe8ee6
Revises: 849eb3e11baa
Create Date: 2026-07-22 18:58:57.363978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '269efebe8ee6'
down_revision: Union[str, Sequence[str], None] = '849eb3e11baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interviews",sa.Column("retrieval_summary", sa.TEXT))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interviews", "retrieval_summary")
    # ### end Alembic commands ###
