"""mig_08_indexing_in_embeddings

Revision ID: 3428e40f6620
Revises: ef75622436a2
Create Date: 2026-06-18 12:35:59.056195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3428e40f6620'
down_revision: Union[str, Sequence[str], None] = 'ef75622436a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS question_embedding_hnsw_idx
        ON questions
        USING hnsw (embedding vector_cosine_ops);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP INDEX IF EXISTS question_embedding_hnsw_idx;
        """
    )
    # ### end Alembic commands ###
