"""retrieval_embedding_column

Revision ID: 7b0bbc9c4c4c
Revises: 269efebe8ee6
Create Date: 2026-08-26 19:10:26.034540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '7b0bbc9c4c4c'
down_revision: Union[str, Sequence[str], None] = '269efebe8ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interviews",
        sa.Column(
            "retrieval_embedding",
            Vector(384),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interviews", "retrieval_embedding")
    # ### end Alembic commands ###
