"""adding_few_more_contextual_field_to_questions_model

Revision ID: 83b978f8849a
Revises: a1b2c3d4e5f6
Create Date: 2026-06-05 17:35:42.823712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83b978f8849a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'skills')
    # ### end Alembic commands ###
