"""store_cosine_distance

Revision ID: 849eb3e11baa
Revises: feae8f8e9da8
Create Date: 2026-07-20 17:53:24.912689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '849eb3e11baa'
down_revision: Union[str, Sequence[str], None] = 'feae8f8e9da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_questions",
        sa.Column("distance", sa.Float(), nullable=True)
    )

    op.add_column(
        "interview_questions",
        sa.Column("similarity", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_questions", "similarity")
    op.drop_column("interview_questions", "distance")
    # ### end Alembic commands ###
