"""vector_columns_added

Revision ID: 8add84a7dc93
Revises: c01651482ed0
Create Date: 2026-06-17 10:49:04.608829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '8add84a7dc93'
down_revision: Union[str, Sequence[str], None] = 'c01651482ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE EXTENSION IF NOT EXISTS vector"
    )
    op.add_column(
        "questions",
        sa.Column(
            "embedding",
            Vector(384),
            nullable=True
        )
    )
    # interview_questions table
    op.add_column(
        "interview_questions",
        sa.Column(
            "original_question",
            sa.Text(),
            nullable=True
        )
    )

    op.add_column(
        "interview_questions",
        sa.Column(
            "personalized_question",
            sa.Text(),
            nullable=True
        )
    )

    op.add_column(
        "interview_questions",
        sa.Column(
            "expected_answer",
            sa.Text(),
            nullable=True
        )
    )

    op.add_column(
        "interview_questions",
        sa.Column(
            "user_answer",
            sa.Text(),
            nullable=True
        )
    )

    op.add_column(
        "interview_questions",
        sa.Column(
            "score",
            sa.Float(),
            nullable=True
        )
    )

    op.add_column(
        "interview_questions",
        sa.Column(
            "feedback",
            sa.Text(),
            nullable=True
        )
    )

    op.drop_column(
        "interview_questions",
        "order_no"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_questions",
        sa.Column(
            "order_no",
            sa.Integer(),
            nullable=True
        )
    )

    op.drop_column(
        "interview_questions",
        "feedback"
    )

    op.drop_column(
        "interview_questions",
        "score"
    )

    op.drop_column(
        "interview_questions",
        "user_answer"
    )

    op.drop_column(
        "interview_questions",
        "expected_answer"
    )

    op.drop_column(
        "interview_questions",
        "personalized_question"
    )

    op.drop_column(
        "interview_questions",
        "original_question"
    )

    op.drop_column(
        "questions",
        "embedding"
    )
    # ### end Alembic commands ###
