"""enhanced_interview_session_summary

Revision ID: 8cba4ff3a2b0
Revises: e511586a6cf6
Create Date: 2026-06-25 13:45:27.002572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cba4ff3a2b0'
down_revision: Union[str, Sequence[str], None] = 'e511586a6cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('interviews', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('interviews', sa.Column('overall_summary', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('overall_strengths', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('interviews', sa.Column('overall_gaps', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('interviews', sa.Column('recommendation', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('communication_score', sa.Float(), nullable=True))
    op.add_column('interviews', sa.Column('technical_score', sa.Float(), nullable=True))
    op.add_column('interviews', sa.Column('learning_plan', sa.ARRAY(sa.String(255)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'learning_plan')
    op.drop_column('interviews', 'technical_score')
    op.drop_column('interviews', 'communication_score')
    op.drop_column('interviews', 'recommendation')
    op.drop_column('interviews', 'overall_gaps')
    op.drop_column('interviews', 'overall_strengths')
    op.drop_column('interviews', 'overall_summary')
    op.drop_column('interviews', 'overall_score')

    # ### end Alembic commands ###
