"""interview_question_model_changes

Revision ID: de87d9224a8e
Revises: 3428e40f6620
Create Date: 2026-06-19 11:51:07.708459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de87d9224a8e'
down_revision: Union[str, Sequence[str], None] = '3428e40f6620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interview_questions",sa.Column("original_expected_answer", sa.TEXT))
    # op.add_column("interview_questions",sa.Column("personalized_expected_answer", sa.TEXT))
    op.drop_column("interview_questions", "expected_answer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interview_questions",sa.Column("expected_answer", sa.TEXT))
    # op.drop_column("interview_questions", "personalized_expected_answer")
    op.drop_column("interview_questions", "original_expected_answer")
    # ### end Alembic commands ###
