"""retrieval_distance_n_similarity

Revision ID: e530fd3de805
Revises: 7b0bbc9c4c4c
Create Date: 2026-08-26 19:42:53.755873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e530fd3de805'
down_revision: Union[str, Sequence[str], None] = '7b0bbc9c4c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_questions", "similarity")
    op.drop_column("interview_questions", "distance")
    op.add_column(
        "interview_questions",
        sa.Column("resume_distance", sa.Float(), nullable=True),
    )
    op.add_column(
        "interview_questions",
        sa.Column("resume_similarity", sa.Float(), nullable=True),
    )
    op.add_column(
        "interview_questions",
        sa.Column("retrieval_distance", sa.Float(), nullable=True),
    )
    op.add_column(
        "interview_questions",
        sa.Column("retrieval_similarity", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_questions", "retrieval_similarity")
    op.drop_column("interview_questions", "retrieval_distance")
    op.drop_column("interview_questions", "resume_similarity")
    op.drop_column("interview_questions", "resume_distance")
    op.add_column(
        "interview_questions",
        sa.Column("distance", sa.Float(), nullable=True),
    )
    op.add_column(
        "interview_questions",
        sa.Column("similarity", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###
