"""vector_embedding_column_for_resume

Revision ID: ef75622436a2
Revises: 8add84a7dc93
Create Date: 2026-06-18 12:04:01.678121

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef75622436a2'
down_revision: Union[str, Sequence[str], None] = '8add84a7dc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interviews",
        sa.Column(
            "resume_embedding",
            Vector(384),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interviews", "resume_embedding")
    # ### end Alembic commands ###
